export { default as IcOrigonPeopleEdit_16Filled } from './IcOrigonPeopleEdit_16Filled';
export { default as IcOrigonPeopleEdit_16Regular } from './IcOrigonPeopleEdit_16Regular';
export { default as IcOrigonPeopleEdit_20Filled } from './IcOrigonPeopleEdit_20Filled';
export { default as IcOrigonPeopleEdit_20Regular } from './IcOrigonPeopleEdit_20Regular';
export { default as IcOrigonPeopleEdit_24Filled } from './IcOrigonPeopleEdit_24Filled';
export { default as IcOrigonPeopleEdit_24Regular } from './IcOrigonPeopleEdit_24Regular';
export { default as IcOrigonPeopleEdit_32Filled } from './IcOrigonPeopleEdit_32Filled';
export { default as IcOrigonPeopleEdit_32Light } from './IcOrigonPeopleEdit_32Light';
export { default as IcOrigonPeopleEdit_32Regular } from './IcOrigonPeopleEdit_32Regular';
