export { default as IcOrigonRibbonStar_20Color } from './IcOrigonRibbonStar_20Color';
export { default as IcOrigonRibbonStar_20Filled } from './IcOrigonRibbonStar_20Filled';
export { default as IcOrigonRibbonStar_20Regular } from './IcOrigonRibbonStar_20Regular';
export { default as IcOrigonRibbonStar_24Color } from './IcOrigonRibbonStar_24Color';
export { default as IcOrigonRibbonStar_24Filled } from './IcOrigonRibbonStar_24Filled';
export { default as IcOrigonRibbonStar_24Regular } from './IcOrigonRibbonStar_24Regular';
export { default as IcOrigonRibbonStar_32Color } from './IcOrigonRibbonStar_32Color';
export { default as IcOrigonRibbonStar_32Filled } from './IcOrigonRibbonStar_32Filled';
export { default as IcOrigonRibbonStar_32Regular } from './IcOrigonRibbonStar_32Regular';
