export { default as IcOrigonCalendarSync_16Color } from './IcOrigonCalendarSync_16Color';
export { default as IcOrigonCalendarSync_16Filled } from './IcOrigonCalendarSync_16Filled';
export { default as IcOrigonCalendarSync_16Regular } from './IcOrigonCalendarSync_16Regular';
export { default as IcOrigonCalendarSync_20Color } from './IcOrigonCalendarSync_20Color';
export { default as IcOrigonCalendarSync_20Filled } from './IcOrigonCalendarSync_20Filled';
export { default as IcOrigonCalendarSync_20Regular } from './IcOrigonCalendarSync_20Regular';
export { default as IcOrigonCalendarSync_24Color } from './IcOrigonCalendarSync_24Color';
export { default as IcOrigonCalendarSync_24Filled } from './IcOrigonCalendarSync_24Filled';
export { default as IcOrigonCalendarSync_24Regular } from './IcOrigonCalendarSync_24Regular';
