export { default as IcFluentCalendarSync_16Color } from './IcFluentCalendarSync_16Color';
export { default as IcFluentCalendarSync_16Filled } from './IcFluentCalendarSync_16Filled';
export { default as IcFluentCalendarSync_16Regular } from './IcFluentCalendarSync_16Regular';
export { default as IcFluentCalendarSync_20Color } from './IcFluentCalendarSync_20Color';
export { default as IcFluentCalendarSync_20Filled } from './IcFluentCalendarSync_20Filled';
export { default as IcFluentCalendarSync_20Regular } from './IcFluentCalendarSync_20Regular';
export { default as IcFluentCalendarSync_24Color } from './IcFluentCalendarSync_24Color';
export { default as IcFluentCalendarSync_24Filled } from './IcFluentCalendarSync_24Filled';
export { default as IcFluentCalendarSync_24Regular } from './IcFluentCalendarSync_24Regular';
