export { default as IcOrigonPeopleCheckmark_16Filled } from './IcOrigonPeopleCheckmark_16Filled';
export { default as IcOrigonPeopleCheckmark_16Regular } from './IcOrigonPeopleCheckmark_16Regular';
export { default as IcOrigonPeopleCheckmark_20Filled } from './IcOrigonPeopleCheckmark_20Filled';
export { default as IcOrigonPeopleCheckmark_20Regular } from './IcOrigonPeopleCheckmark_20Regular';
export { default as IcOrigonPeopleCheckmark_24Filled } from './IcOrigonPeopleCheckmark_24Filled';
export { default as IcOrigonPeopleCheckmark_24Regular } from './IcOrigonPeopleCheckmark_24Regular';
export { default as IcOrigonPeopleCheckmark_32Filled } from './IcOrigonPeopleCheckmark_32Filled';
export { default as IcOrigonPeopleCheckmark_32Light } from './IcOrigonPeopleCheckmark_32Light';
export { default as IcOrigonPeopleCheckmark_32Regular } from './IcOrigonPeopleCheckmark_32Regular';
