export { default as IcFluentLayoutRowTwoSettings_20Filled } from './IcFluentLayoutRowTwoSettings_20Filled';
export { default as IcFluentLayoutRowTwoSettings_20Regular } from './IcFluentLayoutRowTwoSettings_20Regular';
export { default as IcFluentLayoutRowTwoSettings_24Filled } from './IcFluentLayoutRowTwoSettings_24Filled';
export { default as IcFluentLayoutRowTwoSettings_24Regular } from './IcFluentLayoutRowTwoSettings_24Regular';
export { default as IcFluentLayoutRowTwoSettings_28Filled } from './IcFluentLayoutRowTwoSettings_28Filled';
export { default as IcFluentLayoutRowTwoSettings_28Regular } from './IcFluentLayoutRowTwoSettings_28Regular';
export { default as IcFluentLayoutRowTwoSettings_32Filled } from './IcFluentLayoutRowTwoSettings_32Filled';
export { default as IcFluentLayoutRowTwoSettings_32Light } from './IcFluentLayoutRowTwoSettings_32Light';
export { default as IcFluentLayoutRowTwoSettings_32Regular } from './IcFluentLayoutRowTwoSettings_32Regular';
