export { default as IcOrigonLayoutRowTwoSettings_20Filled } from './IcOrigonLayoutRowTwoSettings_20Filled';
export { default as IcOrigonLayoutRowTwoSettings_20Regular } from './IcOrigonLayoutRowTwoSettings_20Regular';
export { default as IcOrigonLayoutRowTwoSettings_24Filled } from './IcOrigonLayoutRowTwoSettings_24Filled';
export { default as IcOrigonLayoutRowTwoSettings_24Regular } from './IcOrigonLayoutRowTwoSettings_24Regular';
export { default as IcOrigonLayoutRowTwoSettings_28Filled } from './IcOrigonLayoutRowTwoSettings_28Filled';
export { default as IcOrigonLayoutRowTwoSettings_28Regular } from './IcOrigonLayoutRowTwoSettings_28Regular';
export { default as IcOrigonLayoutRowTwoSettings_32Filled } from './IcOrigonLayoutRowTwoSettings_32Filled';
export { default as IcOrigonLayoutRowTwoSettings_32Light } from './IcOrigonLayoutRowTwoSettings_32Light';
export { default as IcOrigonLayoutRowTwoSettings_32Regular } from './IcOrigonLayoutRowTwoSettings_32Regular';
