export { default as IcOrigonTableMoveLeft_16Filled } from './IcOrigonTableMoveLeft_16Filled';
export { default as IcOrigonTableMoveLeft_16Regular } from './IcOrigonTableMoveLeft_16Regular';
export { default as IcOrigonTableMoveLeft_20Filled } from './IcOrigonTableMoveLeft_20Filled';
export { default as IcOrigonTableMoveLeft_20Regular } from './IcOrigonTableMoveLeft_20Regular';
export { default as IcOrigonTableMoveLeft_24Filled } from './IcOrigonTableMoveLeft_24Filled';
export { default as IcOrigonTableMoveLeft_24Regular } from './IcOrigonTableMoveLeft_24Regular';
export { default as IcOrigonTableMoveLeft_28Filled } from './IcOrigonTableMoveLeft_28Filled';
export { default as IcOrigonTableMoveLeft_28Regular } from './IcOrigonTableMoveLeft_28Regular';
export { default as IcOrigonTableMoveLeft_32Light } from './IcOrigonTableMoveLeft_32Light';
