export { default as IcOrigonStarSettings_20Color } from './IcOrigonStarSettings_20Color';
export { default as IcOrigonStarSettings_20Filled } from './IcOrigonStarSettings_20Filled';
export { default as IcOrigonStarSettings_20Regular } from './IcOrigonStarSettings_20Regular';
export { default as IcOrigonStarSettings_24Color } from './IcOrigonStarSettings_24Color';
export { default as IcOrigonStarSettings_24Filled } from './IcOrigonStarSettings_24Filled';
export { default as IcOrigonStarSettings_24Regular } from './IcOrigonStarSettings_24Regular';
export { default as IcOrigonStarSettings_32Color } from './IcOrigonStarSettings_32Color';
export { default as IcOrigonStarSettings_32Filled } from './IcOrigonStarSettings_32Filled';
export { default as IcOrigonStarSettings_32Regular } from './IcOrigonStarSettings_32Regular';
