export { default as IcOrigonBookOpenLightbulb_20Color } from './IcOrigonBookOpenLightbulb_20Color';
export { default as IcOrigonBookOpenLightbulb_20Filled } from './IcOrigonBookOpenLightbulb_20Filled';
export { default as IcOrigonBookOpenLightbulb_20Regular } from './IcOrigonBookOpenLightbulb_20Regular';
export { default as IcOrigonBookOpenLightbulb_24Color } from './IcOrigonBookOpenLightbulb_24Color';
export { default as IcOrigonBookOpenLightbulb_24Filled } from './IcOrigonBookOpenLightbulb_24Filled';
export { default as IcOrigonBookOpenLightbulb_24Regular } from './IcOrigonBookOpenLightbulb_24Regular';
export { default as IcOrigonBookOpenLightbulb_32Color } from './IcOrigonBookOpenLightbulb_32Color';
export { default as IcOrigonBookOpenLightbulb_32Filled } from './IcOrigonBookOpenLightbulb_32Filled';
export { default as IcOrigonBookOpenLightbulb_32Regular } from './IcOrigonBookOpenLightbulb_32Regular';
