export { default as IcOrigonReadAloud_16Filled } from './IcOrigonReadAloud_16Filled';
export { default as IcOrigonReadAloud_16Regular } from './IcOrigonReadAloud_16Regular';
export { default as IcOrigonReadAloud_20Filled } from './IcOrigonReadAloud_20Filled';
export { default as IcOrigonReadAloud_20Regular } from './IcOrigonReadAloud_20Regular';
export { default as IcOrigonReadAloud_24Filled } from './IcOrigonReadAloud_24Filled';
export { default as IcOrigonReadAloud_24Regular } from './IcOrigonReadAloud_24Regular';
export { default as IcOrigonReadAloud_28Filled } from './IcOrigonReadAloud_28Filled';
export { default as IcOrigonReadAloud_28Regular } from './IcOrigonReadAloud_28Regular';
export { default as IcOrigonReadAloud_32Light } from './IcOrigonReadAloud_32Light';
