export { default as IcOrigonCode_16Color } from './IcOrigonCode_16Color';
export { default as IcOrigonCode_16Filled } from './IcOrigonCode_16Filled';
export { default as IcOrigonCode_16Regular } from './IcOrigonCode_16Regular';
export { default as IcOrigonCode_20Color } from './IcOrigonCode_20Color';
export { default as IcOrigonCode_20Filled } from './IcOrigonCode_20Filled';
export { default as IcOrigonCode_20Regular } from './IcOrigonCode_20Regular';
export { default as IcOrigonCode_24Color } from './IcOrigonCode_24Color';
export { default as IcOrigonCode_24Filled } from './IcOrigonCode_24Filled';
export { default as IcOrigonCode_24Regular } from './IcOrigonCode_24Regular';
