export { default as IcOrigonWrench_16Color } from './IcOrigonWrench_16Color';
export { default as IcOrigonWrench_16Filled } from './IcOrigonWrench_16Filled';
export { default as IcOrigonWrench_16Regular } from './IcOrigonWrench_16Regular';
export { default as IcOrigonWrench_20Color } from './IcOrigonWrench_20Color';
export { default as IcOrigonWrench_20Filled } from './IcOrigonWrench_20Filled';
export { default as IcOrigonWrench_20Regular } from './IcOrigonWrench_20Regular';
export { default as IcOrigonWrench_24Color } from './IcOrigonWrench_24Color';
export { default as IcOrigonWrench_24Filled } from './IcOrigonWrench_24Filled';
export { default as IcOrigonWrench_24Regular } from './IcOrigonWrench_24Regular';
