export { default as IcOrigonTableDismiss_16Filled } from './IcOrigonTableDismiss_16Filled';
export { default as IcOrigonTableDismiss_16Regular } from './IcOrigonTableDismiss_16Regular';
export { default as IcOrigonTableDismiss_20Filled } from './IcOrigonTableDismiss_20Filled';
export { default as IcOrigonTableDismiss_20Regular } from './IcOrigonTableDismiss_20Regular';
export { default as IcOrigonTableDismiss_24Filled } from './IcOrigonTableDismiss_24Filled';
export { default as IcOrigonTableDismiss_24Regular } from './IcOrigonTableDismiss_24Regular';
export { default as IcOrigonTableDismiss_28Filled } from './IcOrigonTableDismiss_28Filled';
export { default as IcOrigonTableDismiss_28Regular } from './IcOrigonTableDismiss_28Regular';
export { default as IcOrigonTableDismiss_32Light } from './IcOrigonTableDismiss_32Light';
