export { default as IcOrigonDocumentEdit_16Color } from './IcOrigonDocumentEdit_16Color';
export { default as IcOrigonDocumentEdit_16Filled } from './IcOrigonDocumentEdit_16Filled';
export { default as IcOrigonDocumentEdit_16Regular } from './IcOrigonDocumentEdit_16Regular';
export { default as IcOrigonDocumentEdit_20Color } from './IcOrigonDocumentEdit_20Color';
export { default as IcOrigonDocumentEdit_20Filled } from './IcOrigonDocumentEdit_20Filled';
export { default as IcOrigonDocumentEdit_20Regular } from './IcOrigonDocumentEdit_20Regular';
export { default as IcOrigonDocumentEdit_24Color } from './IcOrigonDocumentEdit_24Color';
export { default as IcOrigonDocumentEdit_24Filled } from './IcOrigonDocumentEdit_24Filled';
export { default as IcOrigonDocumentEdit_24Regular } from './IcOrigonDocumentEdit_24Regular';
