export { default as IcOrigonGauge_20Color } from './IcOrigonGauge_20Color';
export { default as IcOrigonGauge_20Filled } from './IcOrigonGauge_20Filled';
export { default as IcOrigonGauge_20Regular } from './IcOrigonGauge_20Regular';
export { default as IcOrigonGauge_24Color } from './IcOrigonGauge_24Color';
export { default as IcOrigonGauge_24Filled } from './IcOrigonGauge_24Filled';
export { default as IcOrigonGauge_24Regular } from './IcOrigonGauge_24Regular';
export { default as IcOrigonGauge_32Color } from './IcOrigonGauge_32Color';
export { default as IcOrigonGauge_32Filled } from './IcOrigonGauge_32Filled';
export { default as IcOrigonGauge_32Regular } from './IcOrigonGauge_32Regular';
