export { default as IcOrigonAutoFitWidth_20Filled } from './IcOrigonAutoFitWidth_20Filled';
export { default as IcOrigonAutoFitWidth_20Regular } from './IcOrigonAutoFitWidth_20Regular';
export { default as IcOrigonAutoFitWidth_24Filled } from './IcOrigonAutoFitWidth_24Filled';
export { default as IcOrigonAutoFitWidth_24Regular } from './IcOrigonAutoFitWidth_24Regular';
export { default as IcOrigonAutoFitWidth_28Filled } from './IcOrigonAutoFitWidth_28Filled';
export { default as IcOrigonAutoFitWidth_28Regular } from './IcOrigonAutoFitWidth_28Regular';
export { default as IcOrigonAutoFitWidth_32Filled } from './IcOrigonAutoFitWidth_32Filled';
export { default as IcOrigonAutoFitWidth_32Light } from './IcOrigonAutoFitWidth_32Light';
export { default as IcOrigonAutoFitWidth_32Regular } from './IcOrigonAutoFitWidth_32Regular';
