export { default as IcOrigonLayerDiagonalPerson_16Color } from './IcOrigonLayerDiagonalPerson_16Color';
export { default as IcOrigonLayerDiagonalPerson_16Filled } from './IcOrigonLayerDiagonalPerson_16Filled';
export { default as IcOrigonLayerDiagonalPerson_16Regular } from './IcOrigonLayerDiagonalPerson_16Regular';
export { default as IcOrigonLayerDiagonalPerson_20Color } from './IcOrigonLayerDiagonalPerson_20Color';
export { default as IcOrigonLayerDiagonalPerson_20Filled } from './IcOrigonLayerDiagonalPerson_20Filled';
export { default as IcOrigonLayerDiagonalPerson_20Regular } from './IcOrigonLayerDiagonalPerson_20Regular';
export { default as IcOrigonLayerDiagonalPerson_24Color } from './IcOrigonLayerDiagonalPerson_24Color';
export { default as IcOrigonLayerDiagonalPerson_24Filled } from './IcOrigonLayerDiagonalPerson_24Filled';
export { default as IcOrigonLayerDiagonalPerson_24Regular } from './IcOrigonLayerDiagonalPerson_24Regular';
