export { default as IcOrigonDataBarVerticalAscending_16Color } from './IcOrigonDataBarVerticalAscending_16Color';
export { default as IcOrigonDataBarVerticalAscending_16Filled } from './IcOrigonDataBarVerticalAscending_16Filled';
export { default as IcOrigonDataBarVerticalAscending_16Regular } from './IcOrigonDataBarVerticalAscending_16Regular';
export { default as IcOrigonDataBarVerticalAscending_20Color } from './IcOrigonDataBarVerticalAscending_20Color';
export { default as IcOrigonDataBarVerticalAscending_20Filled } from './IcOrigonDataBarVerticalAscending_20Filled';
export { default as IcOrigonDataBarVerticalAscending_20Regular } from './IcOrigonDataBarVerticalAscending_20Regular';
export { default as IcOrigonDataBarVerticalAscending_24Color } from './IcOrigonDataBarVerticalAscending_24Color';
export { default as IcOrigonDataBarVerticalAscending_24Filled } from './IcOrigonDataBarVerticalAscending_24Filled';
export { default as IcOrigonDataBarVerticalAscending_24Regular } from './IcOrigonDataBarVerticalAscending_24Regular';
