export { default as IcFluentDataBarVerticalAscending_16Color } from './IcFluentDataBarVerticalAscending_16Color';
export { default as IcFluentDataBarVerticalAscending_16Filled } from './IcFluentDataBarVerticalAscending_16Filled';
export { default as IcFluentDataBarVerticalAscending_16Regular } from './IcFluentDataBarVerticalAscending_16Regular';
export { default as IcFluentDataBarVerticalAscending_20Color } from './IcFluentDataBarVerticalAscending_20Color';
export { default as IcFluentDataBarVerticalAscending_20Filled } from './IcFluentDataBarVerticalAscending_20Filled';
export { default as IcFluentDataBarVerticalAscending_20Regular } from './IcFluentDataBarVerticalAscending_20Regular';
export { default as IcFluentDataBarVerticalAscending_24Color } from './IcFluentDataBarVerticalAscending_24Color';
export { default as IcFluentDataBarVerticalAscending_24Filled } from './IcFluentDataBarVerticalAscending_24Filled';
export { default as IcFluentDataBarVerticalAscending_24Regular } from './IcFluentDataBarVerticalAscending_24Regular';
