export { default as IcOrigonDataArea_20Color } from './IcOrigonDataArea_20Color';
export { default as IcOrigonDataArea_20Filled } from './IcOrigonDataArea_20Filled';
export { default as IcOrigonDataArea_20Regular } from './IcOrigonDataArea_20Regular';
export { default as IcOrigonDataArea_24Color } from './IcOrigonDataArea_24Color';
export { default as IcOrigonDataArea_24Filled } from './IcOrigonDataArea_24Filled';
export { default as IcOrigonDataArea_24Regular } from './IcOrigonDataArea_24Regular';
export { default as IcOrigonDataArea_32Color } from './IcOrigonDataArea_32Color';
export { default as IcOrigonDataArea_32Filled } from './IcOrigonDataArea_32Filled';
export { default as IcOrigonDataArea_32Regular } from './IcOrigonDataArea_32Regular';
