export { default as IcOrigonNumberSymbolSquare_20Color } from './IcOrigonNumberSymbolSquare_20Color';
export { default as IcOrigonNumberSymbolSquare_20Filled } from './IcOrigonNumberSymbolSquare_20Filled';
export { default as IcOrigonNumberSymbolSquare_20Regular } from './IcOrigonNumberSymbolSquare_20Regular';
export { default as IcOrigonNumberSymbolSquare_24Color } from './IcOrigonNumberSymbolSquare_24Color';
export { default as IcOrigonNumberSymbolSquare_24Filled } from './IcOrigonNumberSymbolSquare_24Filled';
export { default as IcOrigonNumberSymbolSquare_24Regular } from './IcOrigonNumberSymbolSquare_24Regular';
export { default as IcOrigonNumberSymbolSquare_32Color } from './IcOrigonNumberSymbolSquare_32Color';
export { default as IcOrigonNumberSymbolSquare_32Filled } from './IcOrigonNumberSymbolSquare_32Filled';
export { default as IcOrigonNumberSymbolSquare_32Regular } from './IcOrigonNumberSymbolSquare_32Regular';
