export { default as IcOrigonWeatherSunnyLow_20Color } from './IcOrigonWeatherSunnyLow_20Color';
export { default as IcOrigonWeatherSunnyLow_20Filled } from './IcOrigonWeatherSunnyLow_20Filled';
export { default as IcOrigonWeatherSunnyLow_20Regular } from './IcOrigonWeatherSunnyLow_20Regular';
export { default as IcOrigonWeatherSunnyLow_24Color } from './IcOrigonWeatherSunnyLow_24Color';
export { default as IcOrigonWeatherSunnyLow_24Filled } from './IcOrigonWeatherSunnyLow_24Filled';
export { default as IcOrigonWeatherSunnyLow_24Regular } from './IcOrigonWeatherSunnyLow_24Regular';
export { default as IcOrigonWeatherSunnyLow_48Color } from './IcOrigonWeatherSunnyLow_48Color';
export { default as IcOrigonWeatherSunnyLow_48Filled } from './IcOrigonWeatherSunnyLow_48Filled';
export { default as IcOrigonWeatherSunnyLow_48Regular } from './IcOrigonWeatherSunnyLow_48Regular';
