export { default as IcOrigonGiftCard_16Color } from './IcOrigonGiftCard_16Color';
export { default as IcOrigonGiftCard_16Filled } from './IcOrigonGiftCard_16Filled';
export { default as IcOrigonGiftCard_16Regular } from './IcOrigonGiftCard_16Regular';
export { default as IcOrigonGiftCard_20Color } from './IcOrigonGiftCard_20Color';
export { default as IcOrigonGiftCard_20Filled } from './IcOrigonGiftCard_20Filled';
export { default as IcOrigonGiftCard_20Regular } from './IcOrigonGiftCard_20Regular';
export { default as IcOrigonGiftCard_24Color } from './IcOrigonGiftCard_24Color';
export { default as IcOrigonGiftCard_24Filled } from './IcOrigonGiftCard_24Filled';
export { default as IcOrigonGiftCard_24Regular } from './IcOrigonGiftCard_24Regular';
