export { default as IcOrigonTableMoveAbove_16Filled } from './IcOrigonTableMoveAbove_16Filled';
export { default as IcOrigonTableMoveAbove_16Regular } from './IcOrigonTableMoveAbove_16Regular';
export { default as IcOrigonTableMoveAbove_20Filled } from './IcOrigonTableMoveAbove_20Filled';
export { default as IcOrigonTableMoveAbove_20Regular } from './IcOrigonTableMoveAbove_20Regular';
export { default as IcOrigonTableMoveAbove_24Filled } from './IcOrigonTableMoveAbove_24Filled';
export { default as IcOrigonTableMoveAbove_24Regular } from './IcOrigonTableMoveAbove_24Regular';
export { default as IcOrigonTableMoveAbove_28Filled } from './IcOrigonTableMoveAbove_28Filled';
export { default as IcOrigonTableMoveAbove_28Regular } from './IcOrigonTableMoveAbove_28Regular';
export { default as IcOrigonTableMoveAbove_32Light } from './IcOrigonTableMoveAbove_32Light';
