export { default as IcOrigonCheckboxPerson_16Color } from './IcOrigonCheckboxPerson_16Color';
export { default as IcOrigonCheckboxPerson_16Filled } from './IcOrigonCheckboxPerson_16Filled';
export { default as IcOrigonCheckboxPerson_16Regular } from './IcOrigonCheckboxPerson_16Regular';
export { default as IcOrigonCheckboxPerson_20Color } from './IcOrigonCheckboxPerson_20Color';
export { default as IcOrigonCheckboxPerson_20Filled } from './IcOrigonCheckboxPerson_20Filled';
export { default as IcOrigonCheckboxPerson_20Regular } from './IcOrigonCheckboxPerson_20Regular';
export { default as IcOrigonCheckboxPerson_24Color } from './IcOrigonCheckboxPerson_24Color';
export { default as IcOrigonCheckboxPerson_24Filled } from './IcOrigonCheckboxPerson_24Filled';
export { default as IcOrigonCheckboxPerson_24Regular } from './IcOrigonCheckboxPerson_24Regular';
