export { default as IcOrigonMailArrowDoubleBack_16Filled } from './IcOrigonMailArrowDoubleBack_16Filled';
export { default as IcOrigonMailArrowDoubleBack_16Regular } from './IcOrigonMailArrowDoubleBack_16Regular';
export { default as IcOrigonMailArrowDoubleBack_20Filled } from './IcOrigonMailArrowDoubleBack_20Filled';
export { default as IcOrigonMailArrowDoubleBack_20Regular } from './IcOrigonMailArrowDoubleBack_20Regular';
export { default as IcOrigonMailArrowDoubleBack_24Filled } from './IcOrigonMailArrowDoubleBack_24Filled';
export { default as IcOrigonMailArrowDoubleBack_24Regular } from './IcOrigonMailArrowDoubleBack_24Regular';
export { default as IcOrigonMailArrowDoubleBack_32Filled } from './IcOrigonMailArrowDoubleBack_32Filled';
export { default as IcOrigonMailArrowDoubleBack_32Light } from './IcOrigonMailArrowDoubleBack_32Light';
export { default as IcOrigonMailArrowDoubleBack_32Regular } from './IcOrigonMailArrowDoubleBack_32Regular';
