export { default as IcOrigonPatient_20Color } from './IcOrigonPatient_20Color';
export { default as IcOrigonPatient_20Filled } from './IcOrigonPatient_20Filled';
export { default as IcOrigonPatient_20Regular } from './IcOrigonPatient_20Regular';
export { default as IcOrigonPatient_24Color } from './IcOrigonPatient_24Color';
export { default as IcOrigonPatient_24Filled } from './IcOrigonPatient_24Filled';
export { default as IcOrigonPatient_24Regular } from './IcOrigonPatient_24Regular';
export { default as IcOrigonPatient_32Color } from './IcOrigonPatient_32Color';
export { default as IcOrigonPatient_32Filled } from './IcOrigonPatient_32Filled';
export { default as IcOrigonPatient_32Regular } from './IcOrigonPatient_32Regular';
