export { default as IcOrigonTableMoveRight_16Filled } from './IcOrigonTableMoveRight_16Filled';
export { default as IcOrigonTableMoveRight_16Regular } from './IcOrigonTableMoveRight_16Regular';
export { default as IcOrigonTableMoveRight_20Filled } from './IcOrigonTableMoveRight_20Filled';
export { default as IcOrigonTableMoveRight_20Regular } from './IcOrigonTableMoveRight_20Regular';
export { default as IcOrigonTableMoveRight_24Filled } from './IcOrigonTableMoveRight_24Filled';
export { default as IcOrigonTableMoveRight_24Regular } from './IcOrigonTableMoveRight_24Regular';
export { default as IcOrigonTableMoveRight_28Filled } from './IcOrigonTableMoveRight_28Filled';
export { default as IcOrigonTableMoveRight_28Regular } from './IcOrigonTableMoveRight_28Regular';
export { default as IcOrigonTableMoveRight_32Light } from './IcOrigonTableMoveRight_32Light';
