export { default as IcOrigonPeopleSettings_20Filled } from './IcOrigonPeopleSettings_20Filled';
export { default as IcOrigonPeopleSettings_20Regular } from './IcOrigonPeopleSettings_20Regular';
export { default as IcOrigonPeopleSettings_24Filled } from './IcOrigonPeopleSettings_24Filled';
export { default as IcOrigonPeopleSettings_24Regular } from './IcOrigonPeopleSettings_24Regular';
export { default as IcOrigonPeopleSettings_28Filled } from './IcOrigonPeopleSettings_28Filled';
export { default as IcOrigonPeopleSettings_28Regular } from './IcOrigonPeopleSettings_28Regular';
export { default as IcOrigonPeopleSettings_32Filled } from './IcOrigonPeopleSettings_32Filled';
export { default as IcOrigonPeopleSettings_32Light } from './IcOrigonPeopleSettings_32Light';
export { default as IcOrigonPeopleSettings_32Regular } from './IcOrigonPeopleSettings_32Regular';
