export { default as IcOrigonColorFill_16Filled } from './IcOrigonColorFill_16Filled';
export { default as IcOrigonColorFill_16Regular } from './IcOrigonColorFill_16Regular';
export { default as IcOrigonColorFill_20Filled } from './IcOrigonColorFill_20Filled';
export { default as IcOrigonColorFill_20Regular } from './IcOrigonColorFill_20Regular';
export { default as IcOrigonColorFill_24Filled } from './IcOrigonColorFill_24Filled';
export { default as IcOrigonColorFill_24Regular } from './IcOrigonColorFill_24Regular';
export { default as IcOrigonColorFill_28Filled } from './IcOrigonColorFill_28Filled';
export { default as IcOrigonColorFill_28Regular } from './IcOrigonColorFill_28Regular';
export { default as IcOrigonColorFill_32Light } from './IcOrigonColorFill_32Light';
