export { default as IcOrigonVault_16Color } from './IcOrigonVault_16Color';
export { default as IcOrigonVault_16Filled } from './IcOrigonVault_16Filled';
export { default as IcOrigonVault_16Regular } from './IcOrigonVault_16Regular';
export { default as IcOrigonVault_20Color } from './IcOrigonVault_20Color';
export { default as IcOrigonVault_20Filled } from './IcOrigonVault_20Filled';
export { default as IcOrigonVault_20Regular } from './IcOrigonVault_20Regular';
export { default as IcOrigonVault_24Color } from './IcOrigonVault_24Color';
export { default as IcOrigonVault_24Filled } from './IcOrigonVault_24Filled';
export { default as IcOrigonVault_24Regular } from './IcOrigonVault_24Regular';
