export { default as IcOrigonMailArrowClockwise_16Filled } from './IcOrigonMailArrowClockwise_16Filled';
export { default as IcOrigonMailArrowClockwise_16Regular } from './IcOrigonMailArrowClockwise_16Regular';
export { default as IcOrigonMailArrowClockwise_20Filled } from './IcOrigonMailArrowClockwise_20Filled';
export { default as IcOrigonMailArrowClockwise_20Regular } from './IcOrigonMailArrowClockwise_20Regular';
export { default as IcOrigonMailArrowClockwise_24Filled } from './IcOrigonMailArrowClockwise_24Filled';
export { default as IcOrigonMailArrowClockwise_24Regular } from './IcOrigonMailArrowClockwise_24Regular';
export { default as IcOrigonMailArrowClockwise_32Filled } from './IcOrigonMailArrowClockwise_32Filled';
export { default as IcOrigonMailArrowClockwise_32Light } from './IcOrigonMailArrowClockwise_32Light';
export { default as IcOrigonMailArrowClockwise_32Regular } from './IcOrigonMailArrowClockwise_32Regular';
