export { default as IcOrigonCalendarReply_16Filled } from './IcOrigonCalendarReply_16Filled';
export { default as IcOrigonCalendarReply_16Regular } from './IcOrigonCalendarReply_16Regular';
export { default as IcOrigonCalendarReply_20Filled } from './IcOrigonCalendarReply_20Filled';
export { default as IcOrigonCalendarReply_20Regular } from './IcOrigonCalendarReply_20Regular';
export { default as IcOrigonCalendarReply_24Filled } from './IcOrigonCalendarReply_24Filled';
export { default as IcOrigonCalendarReply_24Regular } from './IcOrigonCalendarReply_24Regular';
export { default as IcOrigonCalendarReply_28Filled } from './IcOrigonCalendarReply_28Filled';
export { default as IcOrigonCalendarReply_28Regular } from './IcOrigonCalendarReply_28Regular';
export { default as IcOrigonCalendarReply_32Light } from './IcOrigonCalendarReply_32Light';
