export { default as IcOrigonLayoutColumnTwo_16Filled } from './IcOrigonLayoutColumnTwo_16Filled';
export { default as IcOrigonLayoutColumnTwo_16Regular } from './IcOrigonLayoutColumnTwo_16Regular';
export { default as IcOrigonLayoutColumnTwo_20Filled } from './IcOrigonLayoutColumnTwo_20Filled';
export { default as IcOrigonLayoutColumnTwo_20Regular } from './IcOrigonLayoutColumnTwo_20Regular';
export { default as IcOrigonLayoutColumnTwo_24Filled } from './IcOrigonLayoutColumnTwo_24Filled';
export { default as IcOrigonLayoutColumnTwo_24Regular } from './IcOrigonLayoutColumnTwo_24Regular';
export { default as IcOrigonLayoutColumnTwo_32Filled } from './IcOrigonLayoutColumnTwo_32Filled';
export { default as IcOrigonLayoutColumnTwo_32Light } from './IcOrigonLayoutColumnTwo_32Light';
export { default as IcOrigonLayoutColumnTwo_32Regular } from './IcOrigonLayoutColumnTwo_32Regular';
