export { default as IcOrigonAppsList_20Color } from './IcOrigonAppsList_20Color';
export { default as IcOrigonAppsList_20Filled } from './IcOrigonAppsList_20Filled';
export { default as IcOrigonAppsList_20Regular } from './IcOrigonAppsList_20Regular';
export { default as IcOrigonAppsList_24Color } from './IcOrigonAppsList_24Color';
export { default as IcOrigonAppsList_24Filled } from './IcOrigonAppsList_24Filled';
export { default as IcOrigonAppsList_24Regular } from './IcOrigonAppsList_24Regular';
export { default as IcOrigonAppsList_32Color } from './IcOrigonAppsList_32Color';
export { default as IcOrigonAppsList_32Filled } from './IcOrigonAppsList_32Filled';
export { default as IcOrigonAppsList_32Regular } from './IcOrigonAppsList_32Regular';
