export { default as IcOrigonGift_16Color } from './IcOrigonGift_16Color';
export { default as IcOrigonGift_16Filled } from './IcOrigonGift_16Filled';
export { default as IcOrigonGift_16Regular } from './IcOrigonGift_16Regular';
export { default as IcOrigonGift_20Color } from './IcOrigonGift_20Color';
export { default as IcOrigonGift_20Filled } from './IcOrigonGift_20Filled';
export { default as IcOrigonGift_20Regular } from './IcOrigonGift_20Regular';
export { default as IcOrigonGift_24Color } from './IcOrigonGift_24Color';
export { default as IcOrigonGift_24Filled } from './IcOrigonGift_24Filled';
export { default as IcOrigonGift_24Regular } from './IcOrigonGift_24Regular';
