export { default as IcOrigonTranslate_16Filled } from './IcOrigonTranslate_16Filled';
export { default as IcOrigonTranslate_16Regular } from './IcOrigonTranslate_16Regular';
export { default as IcOrigonTranslate_20Filled } from './IcOrigonTranslate_20Filled';
export { default as IcOrigonTranslate_20Regular } from './IcOrigonTranslate_20Regular';
export { default as IcOrigonTranslate_24Filled } from './IcOrigonTranslate_24Filled';
export { default as IcOrigonTranslate_24Regular } from './IcOrigonTranslate_24Regular';
export { default as IcOrigonTranslate_32Filled } from './IcOrigonTranslate_32Filled';
export { default as IcOrigonTranslate_32Light } from './IcOrigonTranslate_32Light';
export { default as IcOrigonTranslate_32Regular } from './IcOrigonTranslate_32Regular';
