export { default as IcOrigonAppsListDetail_20Color } from './IcOrigonAppsListDetail_20Color';
export { default as IcOrigonAppsListDetail_20Filled } from './IcOrigonAppsListDetail_20Filled';
export { default as IcOrigonAppsListDetail_20Regular } from './IcOrigonAppsListDetail_20Regular';
export { default as IcOrigonAppsListDetail_24Color } from './IcOrigonAppsListDetail_24Color';
export { default as IcOrigonAppsListDetail_24Filled } from './IcOrigonAppsListDetail_24Filled';
export { default as IcOrigonAppsListDetail_24Regular } from './IcOrigonAppsListDetail_24Regular';
export { default as IcOrigonAppsListDetail_32Color } from './IcOrigonAppsListDetail_32Color';
export { default as IcOrigonAppsListDetail_32Filled } from './IcOrigonAppsListDetail_32Filled';
export { default as IcOrigonAppsListDetail_32Regular } from './IcOrigonAppsListDetail_32Regular';
