export { default as IcOrigonArrowSquareDown_20Color } from './IcOrigonArrowSquareDown_20Color';
export { default as IcOrigonArrowSquareDown_20Filled } from './IcOrigonArrowSquareDown_20Filled';
export { default as IcOrigonArrowSquareDown_20Regular } from './IcOrigonArrowSquareDown_20Regular';
export { default as IcOrigonArrowSquareDown_24Color } from './IcOrigonArrowSquareDown_24Color';
export { default as IcOrigonArrowSquareDown_24Filled } from './IcOrigonArrowSquareDown_24Filled';
export { default as IcOrigonArrowSquareDown_24Regular } from './IcOrigonArrowSquareDown_24Regular';
export { default as IcOrigonArrowSquareDown_32Color } from './IcOrigonArrowSquareDown_32Color';
export { default as IcOrigonArrowSquareDown_32Filled } from './IcOrigonArrowSquareDown_32Filled';
export { default as IcOrigonArrowSquareDown_32Regular } from './IcOrigonArrowSquareDown_32Regular';
