export { default as IcOrigonTableMoveBelow_16Filled } from './IcOrigonTableMoveBelow_16Filled';
export { default as IcOrigonTableMoveBelow_16Regular } from './IcOrigonTableMoveBelow_16Regular';
export { default as IcOrigonTableMoveBelow_20Filled } from './IcOrigonTableMoveBelow_20Filled';
export { default as IcOrigonTableMoveBelow_20Regular } from './IcOrigonTableMoveBelow_20Regular';
export { default as IcOrigonTableMoveBelow_24Filled } from './IcOrigonTableMoveBelow_24Filled';
export { default as IcOrigonTableMoveBelow_24Regular } from './IcOrigonTableMoveBelow_24Regular';
export { default as IcOrigonTableMoveBelow_28Filled } from './IcOrigonTableMoveBelow_28Filled';
export { default as IcOrigonTableMoveBelow_28Regular } from './IcOrigonTableMoveBelow_28Regular';
export { default as IcOrigonTableMoveBelow_32Light } from './IcOrigonTableMoveBelow_32Light';
