export { default as IcOrigonClipboardPaste_16Filled } from './IcOrigonClipboardPaste_16Filled';
export { default as IcOrigonClipboardPaste_16Regular } from './IcOrigonClipboardPaste_16Regular';
export { default as IcOrigonClipboardPaste_20Filled } from './IcOrigonClipboardPaste_20Filled';
export { default as IcOrigonClipboardPaste_20Regular } from './IcOrigonClipboardPaste_20Regular';
export { default as IcOrigonClipboardPaste_24Filled } from './IcOrigonClipboardPaste_24Filled';
export { default as IcOrigonClipboardPaste_24Regular } from './IcOrigonClipboardPaste_24Regular';
export { default as IcOrigonClipboardPaste_32Filled } from './IcOrigonClipboardPaste_32Filled';
export { default as IcOrigonClipboardPaste_32Light } from './IcOrigonClipboardPaste_32Light';
export { default as IcOrigonClipboardPaste_32Regular } from './IcOrigonClipboardPaste_32Regular';
