export { default as IcOrigonDataScatter_20Color } from './IcOrigonDataScatter_20Color';
export { default as IcOrigonDataScatter_20Filled } from './IcOrigonDataScatter_20Filled';
export { default as IcOrigonDataScatter_20Regular } from './IcOrigonDataScatter_20Regular';
export { default as IcOrigonDataScatter_24Color } from './IcOrigonDataScatter_24Color';
export { default as IcOrigonDataScatter_24Filled } from './IcOrigonDataScatter_24Filled';
export { default as IcOrigonDataScatter_24Regular } from './IcOrigonDataScatter_24Regular';
export { default as IcOrigonDataScatter_32Color } from './IcOrigonDataScatter_32Color';
export { default as IcOrigonDataScatter_32Filled } from './IcOrigonDataScatter_32Filled';
export { default as IcOrigonDataScatter_32Regular } from './IcOrigonDataScatter_32Regular';
