export { default as IcOrigonClipboardTask_16Color } from './IcOrigonClipboardTask_16Color';
export { default as IcOrigonClipboardTask_16Filled } from './IcOrigonClipboardTask_16Filled';
export { default as IcOrigonClipboardTask_16Regular } from './IcOrigonClipboardTask_16Regular';
export { default as IcOrigonClipboardTask_20Color } from './IcOrigonClipboardTask_20Color';
export { default as IcOrigonClipboardTask_20Filled } from './IcOrigonClipboardTask_20Filled';
export { default as IcOrigonClipboardTask_20Regular } from './IcOrigonClipboardTask_20Regular';
export { default as IcOrigonClipboardTask_24Color } from './IcOrigonClipboardTask_24Color';
export { default as IcOrigonClipboardTask_24Filled } from './IcOrigonClipboardTask_24Filled';
export { default as IcOrigonClipboardTask_24Regular } from './IcOrigonClipboardTask_24Regular';
