export { default as IcOrigonHandDraw_16Filled } from './IcOrigonHandDraw_16Filled';
export { default as IcOrigonHandDraw_16Regular } from './IcOrigonHandDraw_16Regular';
export { default as IcOrigonHandDraw_20Filled } from './IcOrigonHandDraw_20Filled';
export { default as IcOrigonHandDraw_20Regular } from './IcOrigonHandDraw_20Regular';
export { default as IcOrigonHandDraw_24Filled } from './IcOrigonHandDraw_24Filled';
export { default as IcOrigonHandDraw_24Regular } from './IcOrigonHandDraw_24Regular';
export { default as IcOrigonHandDraw_28Filled } from './IcOrigonHandDraw_28Filled';
export { default as IcOrigonHandDraw_28Regular } from './IcOrigonHandDraw_28Regular';
export { default as IcOrigonHandDraw_32Light } from './IcOrigonHandDraw_32Light';
