export { default as IcOrigonTableSettings_16Filled } from './IcOrigonTableSettings_16Filled';
export { default as IcOrigonTableSettings_16Regular } from './IcOrigonTableSettings_16Regular';
export { default as IcOrigonTableSettings_20Filled } from './IcOrigonTableSettings_20Filled';
export { default as IcOrigonTableSettings_20Regular } from './IcOrigonTableSettings_20Regular';
export { default as IcOrigonTableSettings_24Filled } from './IcOrigonTableSettings_24Filled';
export { default as IcOrigonTableSettings_24Regular } from './IcOrigonTableSettings_24Regular';
export { default as IcOrigonTableSettings_28Filled } from './IcOrigonTableSettings_28Filled';
export { default as IcOrigonTableSettings_28Regular } from './IcOrigonTableSettings_28Regular';
export { default as IcOrigonTableSettings_32Light } from './IcOrigonTableSettings_32Light';
