export { default as IcOrigonZoomIn_16Filled } from './IcOrigonZoomIn_16Filled';
export { default as IcOrigonZoomIn_16Regular } from './IcOrigonZoomIn_16Regular';
export { default as IcOrigonZoomIn_20Filled } from './IcOrigonZoomIn_20Filled';
export { default as IcOrigonZoomIn_20Regular } from './IcOrigonZoomIn_20Regular';
export { default as IcOrigonZoomIn_24Filled } from './IcOrigonZoomIn_24Filled';
export { default as IcOrigonZoomIn_24Regular } from './IcOrigonZoomIn_24Regular';
export { default as IcOrigonZoomIn_32Filled } from './IcOrigonZoomIn_32Filled';
export { default as IcOrigonZoomIn_32Light } from './IcOrigonZoomIn_32Light';
export { default as IcOrigonZoomIn_32Regular } from './IcOrigonZoomIn_32Regular';
