export { default as IcOrigonDrafts_16Color } from './IcOrigonDrafts_16Color';
export { default as IcOrigonDrafts_16Filled } from './IcOrigonDrafts_16Filled';
export { default as IcOrigonDrafts_16Regular } from './IcOrigonDrafts_16Regular';
export { default as IcOrigonDrafts_20Color } from './IcOrigonDrafts_20Color';
export { default as IcOrigonDrafts_20Filled } from './IcOrigonDrafts_20Filled';
export { default as IcOrigonDrafts_20Regular } from './IcOrigonDrafts_20Regular';
export { default as IcOrigonDrafts_24Color } from './IcOrigonDrafts_24Color';
export { default as IcOrigonDrafts_24Filled } from './IcOrigonDrafts_24Filled';
export { default as IcOrigonDrafts_24Regular } from './IcOrigonDrafts_24Regular';
