export { default as IcOrigonSearchVisual_16Color } from './IcOrigonSearchVisual_16Color';
export { default as IcOrigonSearchVisual_16Filled } from './IcOrigonSearchVisual_16Filled';
export { default as IcOrigonSearchVisual_16Regular } from './IcOrigonSearchVisual_16Regular';
export { default as IcOrigonSearchVisual_20Color } from './IcOrigonSearchVisual_20Color';
export { default as IcOrigonSearchVisual_20Filled } from './IcOrigonSearchVisual_20Filled';
export { default as IcOrigonSearchVisual_20Regular } from './IcOrigonSearchVisual_20Regular';
export { default as IcOrigonSearchVisual_24Color } from './IcOrigonSearchVisual_24Color';
export { default as IcOrigonSearchVisual_24Filled } from './IcOrigonSearchVisual_24Filled';
export { default as IcOrigonSearchVisual_24Regular } from './IcOrigonSearchVisual_24Regular';
