export { default as IcOrigonAppGeneric_20Filled } from './IcOrigonAppGeneric_20Filled';
export { default as IcOrigonAppGeneric_20Regular } from './IcOrigonAppGeneric_20Regular';
export { default as IcOrigonAppGeneric_24Filled } from './IcOrigonAppGeneric_24Filled';
export { default as IcOrigonAppGeneric_24Regular } from './IcOrigonAppGeneric_24Regular';
export { default as IcOrigonAppGeneric_32Filled } from './IcOrigonAppGeneric_32Filled';
export { default as IcOrigonAppGeneric_32Light } from './IcOrigonAppGeneric_32Light';
export { default as IcOrigonAppGeneric_32Regular } from './IcOrigonAppGeneric_32Regular';
export { default as IcOrigonAppGeneric_48Filled } from './IcOrigonAppGeneric_48Filled';
export { default as IcOrigonAppGeneric_48Regular } from './IcOrigonAppGeneric_48Regular';
