export { default as IcOrigonBuildingPeople_16Color } from './IcOrigonBuildingPeople_16Color';
export { default as IcOrigonBuildingPeople_16Filled } from './IcOrigonBuildingPeople_16Filled';
export { default as IcOrigonBuildingPeople_16Regular } from './IcOrigonBuildingPeople_16Regular';
export { default as IcOrigonBuildingPeople_20Color } from './IcOrigonBuildingPeople_20Color';
export { default as IcOrigonBuildingPeople_20Filled } from './IcOrigonBuildingPeople_20Filled';
export { default as IcOrigonBuildingPeople_20Regular } from './IcOrigonBuildingPeople_20Regular';
export { default as IcOrigonBuildingPeople_24Color } from './IcOrigonBuildingPeople_24Color';
export { default as IcOrigonBuildingPeople_24Filled } from './IcOrigonBuildingPeople_24Filled';
export { default as IcOrigonBuildingPeople_24Regular } from './IcOrigonBuildingPeople_24Regular';
