export { default as IcFluentBuildingPeople_16Color } from './IcFluentBuildingPeople_16Color';
export { default as IcFluentBuildingPeople_16Filled } from './IcFluentBuildingPeople_16Filled';
export { default as IcFluentBuildingPeople_16Regular } from './IcFluentBuildingPeople_16Regular';
export { default as IcFluentBuildingPeople_20Color } from './IcFluentBuildingPeople_20Color';
export { default as IcFluentBuildingPeople_20Filled } from './IcFluentBuildingPeople_20Filled';
export { default as IcFluentBuildingPeople_20Regular } from './IcFluentBuildingPeople_20Regular';
export { default as IcFluentBuildingPeople_24Color } from './IcFluentBuildingPeople_24Color';
export { default as IcFluentBuildingPeople_24Filled } from './IcFluentBuildingPeople_24Filled';
export { default as IcFluentBuildingPeople_24Regular } from './IcFluentBuildingPeople_24Regular';
