export { default as IcOrigonPersonKey_20Color } from './IcOrigonPersonKey_20Color';
export { default as IcOrigonPersonKey_20Filled } from './IcOrigonPersonKey_20Filled';
export { default as IcOrigonPersonKey_20Regular } from './IcOrigonPersonKey_20Regular';
export { default as IcOrigonPersonKey_24Color } from './IcOrigonPersonKey_24Color';
export { default as IcOrigonPersonKey_24Filled } from './IcOrigonPersonKey_24Filled';
export { default as IcOrigonPersonKey_24Regular } from './IcOrigonPersonKey_24Regular';
export { default as IcOrigonPersonKey_32Color } from './IcOrigonPersonKey_32Color';
export { default as IcOrigonPersonKey_32Filled } from './IcOrigonPersonKey_32Filled';
export { default as IcOrigonPersonKey_32Regular } from './IcOrigonPersonKey_32Regular';
