export { default as IcOrigonAlertUrgent_16Color } from './IcOrigonAlertUrgent_16Color';
export { default as IcOrigonAlertUrgent_16Filled } from './IcOrigonAlertUrgent_16Filled';
export { default as IcOrigonAlertUrgent_16Regular } from './IcOrigonAlertUrgent_16Regular';
export { default as IcOrigonAlertUrgent_20Color } from './IcOrigonAlertUrgent_20Color';
export { default as IcOrigonAlertUrgent_20Filled } from './IcOrigonAlertUrgent_20Filled';
export { default as IcOrigonAlertUrgent_20Regular } from './IcOrigonAlertUrgent_20Regular';
export { default as IcOrigonAlertUrgent_24Color } from './IcOrigonAlertUrgent_24Color';
export { default as IcOrigonAlertUrgent_24Filled } from './IcOrigonAlertUrgent_24Filled';
export { default as IcOrigonAlertUrgent_24Regular } from './IcOrigonAlertUrgent_24Regular';
