export { default as IcOrigonSport_16Color } from './IcOrigonSport_16Color';
export { default as IcOrigonSport_16Filled } from './IcOrigonSport_16Filled';
export { default as IcOrigonSport_16Regular } from './IcOrigonSport_16Regular';
export { default as IcOrigonSport_20Color } from './IcOrigonSport_20Color';
export { default as IcOrigonSport_20Filled } from './IcOrigonSport_20Filled';
export { default as IcOrigonSport_20Regular } from './IcOrigonSport_20Regular';
export { default as IcOrigonSport_24Color } from './IcOrigonSport_24Color';
export { default as IcOrigonSport_24Filled } from './IcOrigonSport_24Filled';
export { default as IcOrigonSport_24Regular } from './IcOrigonSport_24Regular';
