export { default as IcOrigonTableCellsMerge_16Filled } from './IcOrigonTableCellsMerge_16Filled';
export { default as IcOrigonTableCellsMerge_16Regular } from './IcOrigonTableCellsMerge_16Regular';
export { default as IcOrigonTableCellsMerge_20Filled } from './IcOrigonTableCellsMerge_20Filled';
export { default as IcOrigonTableCellsMerge_20Regular } from './IcOrigonTableCellsMerge_20Regular';
export { default as IcOrigonTableCellsMerge_24Filled } from './IcOrigonTableCellsMerge_24Filled';
export { default as IcOrigonTableCellsMerge_24Regular } from './IcOrigonTableCellsMerge_24Regular';
export { default as IcOrigonTableCellsMerge_28Filled } from './IcOrigonTableCellsMerge_28Filled';
export { default as IcOrigonTableCellsMerge_28Regular } from './IcOrigonTableCellsMerge_28Regular';
export { default as IcOrigonTableCellsMerge_32Light } from './IcOrigonTableCellsMerge_32Light';
