export { default as IcOrigonTableCellsSplit_16Filled } from './IcOrigonTableCellsSplit_16Filled';
export { default as IcOrigonTableCellsSplit_16Regular } from './IcOrigonTableCellsSplit_16Regular';
export { default as IcOrigonTableCellsSplit_20Filled } from './IcOrigonTableCellsSplit_20Filled';
export { default as IcOrigonTableCellsSplit_20Regular } from './IcOrigonTableCellsSplit_20Regular';
export { default as IcOrigonTableCellsSplit_24Filled } from './IcOrigonTableCellsSplit_24Filled';
export { default as IcOrigonTableCellsSplit_24Regular } from './IcOrigonTableCellsSplit_24Regular';
export { default as IcOrigonTableCellsSplit_28Filled } from './IcOrigonTableCellsSplit_28Filled';
export { default as IcOrigonTableCellsSplit_28Regular } from './IcOrigonTableCellsSplit_28Regular';
export { default as IcOrigonTableCellsSplit_32Light } from './IcOrigonTableCellsSplit_32Light';
