export { default as IcOrigonLayoutColumnTwoSplitRightFocusBottomRight_16Filled } from './IcOrigonLayoutColumnTwoSplitRightFocusBottomRight_16Filled';
export { default as IcOrigonLayoutColumnTwoSplitRightFocusBottomRight_20Filled } from './IcOrigonLayoutColumnTwoSplitRightFocusBottomRight_20Filled';
export { default as IcOrigonLayoutColumnTwoSplitRightFocusBottomRight_24Filled } from './IcOrigonLayoutColumnTwoSplitRightFocusBottomRight_24Filled';
