export { default as IcOrigonCalendar_3Day_16Filled } from './IcOrigonCalendar_3Day_16Filled';
export { default as IcOrigonCalendar_3Day_16Regular } from './IcOrigonCalendar_3Day_16Regular';
export { default as IcOrigonCalendar_3Day_20Filled } from './IcOrigonCalendar_3Day_20Filled';
export { default as IcOrigonCalendar_3Day_20Regular } from './IcOrigonCalendar_3Day_20Regular';
export { default as IcOrigonCalendar_3Day_24Filled } from './IcOrigonCalendar_3Day_24Filled';
export { default as IcOrigonCalendar_3Day_24Regular } from './IcOrigonCalendar_3Day_24Regular';
export { default as IcOrigonCalendar_3Day_28Filled } from './IcOrigonCalendar_3Day_28Filled';
export { default as IcOrigonCalendar_3Day_28Regular } from './IcOrigonCalendar_3Day_28Regular';
export { default as IcOrigonCalendar_3Day_32Light } from './IcOrigonCalendar_3Day_32Light';
