export { default as IcOrigonDoorArrowRight_16Filled } from './IcOrigonDoorArrowRight_16Filled';
export { default as IcOrigonDoorArrowRight_16Regular } from './IcOrigonDoorArrowRight_16Regular';
export { default as IcOrigonDoorArrowRight_20Filled } from './IcOrigonDoorArrowRight_20Filled';
export { default as IcOrigonDoorArrowRight_20Regular } from './IcOrigonDoorArrowRight_20Regular';
export { default as IcOrigonDoorArrowRight_28Filled } from './IcOrigonDoorArrowRight_28Filled';
export { default as IcOrigonDoorArrowRight_28Regular } from './IcOrigonDoorArrowRight_28Regular';
export { default as IcOrigonDoorArrowRight_32Filled } from './IcOrigonDoorArrowRight_32Filled';
export { default as IcOrigonDoorArrowRight_32Light } from './IcOrigonDoorArrowRight_32Light';
export { default as IcOrigonDoorArrowRight_32Regular } from './IcOrigonDoorArrowRight_32Regular';
