export { default as IcOrigonClassification_16Filled } from './IcOrigonClassification_16Filled';
export { default as IcOrigonClassification_16Regular } from './IcOrigonClassification_16Regular';
export { default as IcOrigonClassification_20Filled } from './IcOrigonClassification_20Filled';
export { default as IcOrigonClassification_20Regular } from './IcOrigonClassification_20Regular';
export { default as IcOrigonClassification_24Filled } from './IcOrigonClassification_24Filled';
export { default as IcOrigonClassification_24Regular } from './IcOrigonClassification_24Regular';
export { default as IcOrigonClassification_32Filled } from './IcOrigonClassification_32Filled';
export { default as IcOrigonClassification_32Light } from './IcOrigonClassification_32Light';
export { default as IcOrigonClassification_32Regular } from './IcOrigonClassification_32Regular';
