export { default as IcOrigonGlobeShield_20Color } from './IcOrigonGlobeShield_20Color';
export { default as IcOrigonGlobeShield_20Filled } from './IcOrigonGlobeShield_20Filled';
export { default as IcOrigonGlobeShield_20Regular } from './IcOrigonGlobeShield_20Regular';
export { default as IcOrigonGlobeShield_24Color } from './IcOrigonGlobeShield_24Color';
export { default as IcOrigonGlobeShield_24Filled } from './IcOrigonGlobeShield_24Filled';
export { default as IcOrigonGlobeShield_24Regular } from './IcOrigonGlobeShield_24Regular';
export { default as IcOrigonGlobeShield_48Color } from './IcOrigonGlobeShield_48Color';
export { default as IcOrigonGlobeShield_48Filled } from './IcOrigonGlobeShield_48Filled';
export { default as IcOrigonGlobeShield_48Regular } from './IcOrigonGlobeShield_48Regular';
