export { default as IcOrigonCalendarCancel_16Color } from './IcOrigonCalendarCancel_16Color';
export { default as IcOrigonCalendarCancel_16Filled } from './IcOrigonCalendarCancel_16Filled';
export { default as IcOrigonCalendarCancel_16Regular } from './IcOrigonCalendarCancel_16Regular';
export { default as IcOrigonCalendarCancel_20Color } from './IcOrigonCalendarCancel_20Color';
export { default as IcOrigonCalendarCancel_20Filled } from './IcOrigonCalendarCancel_20Filled';
export { default as IcOrigonCalendarCancel_20Regular } from './IcOrigonCalendarCancel_20Regular';
export { default as IcOrigonCalendarCancel_24Color } from './IcOrigonCalendarCancel_24Color';
export { default as IcOrigonCalendarCancel_24Filled } from './IcOrigonCalendarCancel_24Filled';
export { default as IcOrigonCalendarCancel_24Regular } from './IcOrigonCalendarCancel_24Regular';
